name: Update Portfolio JSON from Notion

on:
  schedule:
    - cron: "0 * * * *" # runs every hour
  workflow_dispatch: # manual trigger

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install @notionhq/client

      - name: Run Notion → JSON script
        run: node .github/scripts/notion-to-json.js
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

      - name: Commit and push updated JSON
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add src/data/portfolioData.json
          git commit -m "Update portfolioData.json from Notion" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
